#!/usr/bin/env python3
"""
SaaS Evaluator MCP Server
Multi-persona enterprise SaaS evaluation engine — SaaS Usability Index (U-Index)
Generated by Autonomyx / mcp-from-apidocs skill
"""
import os
import json
import httpx
from pathlib import Path
from mcp.server.fastmcp import FastMCP

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
DATA_DIR = Path(os.environ.get("EVAL_DATA_DIR", "/tmp/saas-evaluator-data"))
DATA_DIR.mkdir(parents=True, exist_ok=True)

mcp = FastMCP("saas-evaluator-mcp")

# ─── CONSTANTS ────────────────────────────────────────────────────────────────

STAGES = [
    {"id": 1, "name": "Pre-Purchase / Discovery",       "weight": 0.10},
    {"id": 2, "name": "Vendor Evaluation & Selection",  "weight": 0.20},
    {"id": 3, "name": "Onboarding & Implementation",    "weight": 0.12},
    {"id": 4, "name": "Identity & Access Configuration","weight": 0.18},
    {"id": 5, "name": "Operations & Governance",        "weight": 0.20},
    {"id": 6, "name": "Commercial Lifecycle",           "weight": 0.10},
    {"id": 7, "name": "Risk, Exit & Replacement",       "weight": 0.10},
]

METRICS = [
    {"id": "1.1", "stage": 1, "name": "Feature Parity with Competitors",         "owner": "procurement"},
    {"id": "1.2", "stage": 1, "name": "Roadmap Publishing",                      "owner": "procurement"},
    {"id": "1.3", "stage": 1, "name": "Roadmap Clarity",                         "owner": "cto"},
    {"id": "1.4", "stage": 1, "name": "Thought Leadership",                      "owner": "dept-head"},
    {"id": "1.5", "stage": 1, "name": "Design System Maturity",                  "owner": "dept-head"},
    {"id": "1.6", "stage": 1, "name": "Pricing Transparency",                    "owner": "procurement"},
    {"id": "2.1", "stage": 2, "name": "API Coverage",                            "owner": "cto"},
    {"id": "2.2", "stage": 2, "name": "Automation Coverage",                     "owner": "cto"},
    {"id": "2.3", "stage": 2, "name": "Login Methods + SSO",                     "owner": "ciso"},
    {"id": "2.4", "stage": 2, "name": "RBAC Granularity",                        "owner": "ciso"},
    {"id": "2.5", "stage": 2, "name": "Compliance Coverage",                     "owner": "ciso"},
    {"id": "2.6", "stage": 2, "name": "Activity Logging",                        "owner": "ciso"},
    {"id": "2.7", "stage": 2, "name": "Support SLAs",                            "owner": "it-admin"},
    {"id": "2.8", "stage": 2, "name": "Financial Runway / Vendor Stability",     "owner": "procurement"},
    {"id": "3.1", "stage": 3, "name": "Blueprints, Templates & Walkthroughs",   "owner": "it-admin"},
    {"id": "3.2", "stage": 3, "name": "Data Ingestion Mechanisms",               "owner": "it-admin"},
    {"id": "3.3", "stage": 3, "name": "Data Correction Tools",                   "owner": "it-admin"},
    {"id": "3.4", "stage": 3, "name": "Multi-Device Support",                    "owner": "dept-head"},
    {"id": "3.5", "stage": 3, "name": "Time to Value",                           "owner": "cto"},
    {"id": "3.6", "stage": 3, "name": "Support During Onboarding",               "owner": "dept-head"},
    {"id": "4.1", "stage": 4, "name": "SSO + MFA Enforcement",                  "owner": "ciso"},
    {"id": "4.2", "stage": 4, "name": "User Provisioning Automation (SCIM)",    "owner": "ciso"},
    {"id": "4.3", "stage": 4, "name": "IGA Coverage",                           "owner": "ciso"},
    {"id": "4.4", "stage": 4, "name": "Privileged Access Controls",             "owner": "ciso"},
    {"id": "4.5", "stage": 4, "name": "Multi-Org / Multi-Tenant Support",       "owner": "ciso"},
    {"id": "5.1", "stage": 5, "name": "Compliance Automation",                  "owner": "legal"},
    {"id": "5.2", "stage": 5, "name": "Audit Log Completeness & Retention",     "owner": "ciso"},
    {"id": "5.3", "stage": 5, "name": "Automated Remediation",                  "owner": "it-admin"},
    {"id": "5.4", "stage": 5, "name": "Collaboration Governance",               "owner": "dept-head"},
    {"id": "5.5", "stage": 5, "name": "Partner Ecosystem",                      "owner": "it-admin"},
    {"id": "6.1", "stage": 6, "name": "Pricing Model & Scaling",                "owner": "procurement"},
    {"id": "6.2", "stage": 6, "name": "Roadmap Delivery History",               "owner": "procurement"},
    {"id": "6.3", "stage": 6, "name": "Customer Advocacy",                      "owner": "procurement"},
    {"id": "6.4", "stage": 6, "name": "Dedicated Support Escalation",           "owner": "procurement"},
    {"id": "7.1", "stage": 7, "name": "Data Portability & Export Tooling",      "owner": "legal"},
    {"id": "7.2", "stage": 7, "name": "Vendor Lock-in Avoidance",               "owner": "legal"},
    {"id": "7.3", "stage": 7, "name": "Immutable Logs for Offboarding",         "owner": "legal"},
    {"id": "7.4", "stage": 7, "name": "Zero-Touch Deprovisioning",              "owner": "legal"},
]

VERDICT_THRESHOLDS = [
    {"min": 4.0, "label": "Strong",              "sub": "Recommended"},
    {"min": 3.0, "label": "Enterprise Baseline", "sub": "Approvable with monitoring"},
    {"min": 2.0, "label": "Emerging",            "sub": "Conditional — vendor commitments required"},
    {"min": 0.0, "label": "Not Enterprise-Ready","sub": "Do Not Procure"},
]

# ─── HELPERS ──────────────────────────────────────────────────────────────────

def slugify(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")

def state_path(slug: str) -> Path:
    return DATA_DIR / f"{slug}.json"

def load_state(slug: str) -> dict:
    p = state_path(slug)
    if p.exists():
        return json.loads(p.read_text())
    return {}

def save_state(slug: str, state: dict):
    state_path(slug).write_text(json.dumps(state, indent=2))

def calc_u_index(scores: dict) -> float:
    total = 0.0
    for stage in STAGES:
        stage_metrics = [m for m in METRICS if m["stage"] == stage["id"]]
        scored = [m for m in stage_metrics if scores.get(m["id"]) is not None]
        if not scored:
            continue
        stage_sum = sum(scores[m["id"]] for m in scored)
        stage_score = (stage_sum / (len(stage_metrics) * 5)) * 5
        total += stage_score * stage["weight"]
    return round(total, 2)

def get_verdict(score: float) -> dict:
    for v in VERDICT_THRESHOLDS:
        if score >= v["min"]:
            return v
    return VERDICT_THRESHOLDS[-1]

def get_blockers(scores: dict) -> list:
    return [
        m for m in METRICS
        if m["stage"] in (2, 4, 5)
        and scores.get(m["id"]) is not None
        and scores[m["id"]] <= 1
    ]

def claude_score(product: str, use_case: str, batch: list) -> dict:
    """Call Claude API to score a batch of metrics."""
    if not ANTHROPIC_API_KEY:
        # Fallback: return neutral scores if no API key
        return {"scores": {m["id"]: 3 for m in batch}, "evidence": {m["id"]: "Fallback score — set ANTHROPIC_API_KEY for AI research" for m in batch}}
    
    prompt_lines = "\n".join(f"{m['id']}: {m['name']}" for m in batch)
    system = (
        f'You are a SaaS enterprise evaluator. Score the following metrics for "{product}" '
        f'(use case: {use_case or "general enterprise"}). '
        'Return ONLY valid JSON: {"scores":{"metric_id": score_0_to_5}, "evidence":{"metric_id": "brief evidence"}} '
        'Score 0-5 integers. Be realistic and conservative. No extra text.'
    )
    resp = httpx.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_API_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 1000,
            "system": system,
            "messages": [{"role": "user", "content": prompt_lines}],
        },
        timeout=60,
    )
    resp.raise_for_status()
    text = resp.json()["content"][0]["text"]
    clean = text.replace("```json", "").replace("```", "").strip()
    parsed = json.loads(clean)
    return parsed

# ─── MCP TOOLS ────────────────────────────────────────────────────────────────

@mcp.tool()
def start_evaluation(product_name: str, use_case: str = "") -> dict:
    """
    Start a new SaaS evaluation for a product. Claude auto-researches all 35 metrics
    across 7 procurement stages and pre-populates scores with evidence.

    Args:
        product_name: Name of the SaaS product to evaluate (e.g. "Notion", "Rippling")
        use_case: Optional primary use case (e.g. "Team wiki and knowledge management")

    Returns:
        Evaluation state with auto-researched scores, U-Index, verdict, and any blockers.
    """
    slug = slugify(product_name)
    scores = {}
    evidence = {}

    # Batch research all 35 metrics
    batch_size = 7
    for i in range(0, len(METRICS), batch_size):
        batch = METRICS[i:i + batch_size]
        try:
            result = claude_score(product_name, use_case, batch)
            scores.update(result.get("scores", {}))
            evidence.update(result.get("evidence", {}))
        except Exception as e:
            # On failure, leave metrics unscored for manual input
            pass

    state = {
        "product": product_name,
        "product_slug": slug,
        "use_case": use_case,
        "scores": scores,
        "evidence": evidence,
        "completed_personas": [],
        "alternatives": [],
    }
    save_state(slug, state)

    u_index = calc_u_index(scores)
    verdict = get_verdict(u_index)
    blockers = get_blockers(scores)

    return {
        "product": product_name,
        "slug": slug,
        "u_index": u_index,
        "verdict": verdict["label"],
        "verdict_detail": verdict["sub"],
        "scored_metrics": len([s for s in scores.values() if s is not None]),
        "total_metrics": len(METRICS),
        "blockers": [{"id": b["id"], "name": b["name"], "score": scores[b["id"]]} for b in blockers],
        "scores": scores,
        "evidence": evidence,
        "message": f"Evaluation started for {product_name}. U-Index: {u_index}/5 ({verdict['label']}). "
                   f"{len(blockers)} procurement blocker(s) detected.",
    }


@mcp.tool()
def score_metric(product_slug: str, metric_id: str, score: int, notes: str = "") -> dict:
    """
    Set or override the score for a specific metric in an evaluation.
    Use this to apply persona-reviewed scores or correct AI-researched scores.

    Args:
        product_slug: Slugified product name (e.g. "notion", "rippling")
        metric_id: Metric ID (e.g. "2.3", "4.1")
        score: Score from 0 to 5 (0=Absent, 3=Baseline, 5=Excellent)
        notes: Optional notes or evidence for this score

    Returns:
        Updated U-Index and blocker status after applying the score.
    """
    if score < 0 or score > 5:
        return {"error": "Score must be between 0 and 5"}

    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'. Run start_evaluation first."}

    metric = next((m for m in METRICS if m["id"] == metric_id), None)
    if not metric:
        return {"error": f"Unknown metric ID '{metric_id}'. Valid IDs: 1.1–7.4"}

    state["scores"][metric_id] = score
    if notes:
        state.setdefault("notes", {})[metric_id] = notes
    save_state(product_slug, state)

    u_index = calc_u_index(state["scores"])
    verdict = get_verdict(u_index)
    blockers = get_blockers(state["scores"])
    is_blocker = metric["stage"] in (2, 4, 5) and score <= 1

    return {
        "metric_id": metric_id,
        "metric_name": metric["name"],
        "score_set": score,
        "is_procurement_blocker": is_blocker,
        "u_index": u_index,
        "verdict": verdict["label"],
        "total_blockers": len(blockers),
        "message": f"Scored {metric_id} ({metric['name']}) = {score}. "
                   + ("🚨 PROCUREMENT BLOCKER — score ≤1 in critical stage. " if is_blocker else "")
                   + f"U-Index now: {u_index}/5 ({verdict['label']})",
    }


@mcp.tool()
def get_evaluation_status(product_slug: str) -> dict:
    """
    Get the current status of an evaluation: U-Index, stage breakdown,
    persona completion, scored metric count, and procurement blockers.

    Args:
        product_slug: Slugified product name (e.g. "notion", "rippling")

    Returns:
        Full evaluation status including stage scores, blockers, and persona status.
    """
    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'. Run start_evaluation first."}

    scores = state.get("scores", {})
    u_index = calc_u_index(scores)
    verdict = get_verdict(u_index)
    blockers = get_blockers(scores)

    stage_breakdown = []
    for stage in STAGES:
        ms = [m for m in METRICS if m["stage"] == stage["id"]]
        scored = [m for m in ms if scores.get(m["id"]) is not None]
        avg = (sum(scores[m["id"]] for m in scored) / (len(ms) * 5) * 5) if scored else 0
        stage_breakdown.append({
            "stage": stage["id"],
            "name": stage["name"],
            "weight": stage["weight"],
            "score": round(avg, 2),
            "scored": len(scored),
            "total": len(ms),
        })

    return {
        "product": state.get("product"),
        "u_index": u_index,
        "verdict": verdict["label"],
        "verdict_detail": verdict["sub"],
        "scored_metrics": len([s for s in scores.values() if s is not None]),
        "total_metrics": len(METRICS),
        "completed_personas": state.get("completed_personas", []),
        "pending_personas": [p for p in ["ciso","it-admin","procurement","cto","legal","dept-head"]
                             if p not in state.get("completed_personas", [])],
        "ready_for_report": len(state.get("completed_personas", [])) == 6,
        "stage_breakdown": stage_breakdown,
        "blockers": [{"id": b["id"], "name": b["name"], "stage": b["stage"], "score": scores[b["id"]]}
                     for b in blockers],
        "alternatives": [a["name"] for a in state.get("alternatives", [])],
    }


@mcp.tool()
def mark_persona_complete(product_slug: str, persona_id: str) -> dict:
    """
    Mark a persona's evaluation section as complete.
    Valid personas: ciso, it-admin, procurement, cto, legal, dept-head

    Args:
        product_slug: Slugified product name
        persona_id: Persona identifier (ciso, it-admin, procurement, cto, legal, dept-head)

    Returns:
        Updated persona completion status and whether the evaluation is ready for report.
    """
    valid = ["ciso", "it-admin", "procurement", "cto", "legal", "dept-head"]
    if persona_id not in valid:
        return {"error": f"Invalid persona. Must be one of: {', '.join(valid)}"}

    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'."}

    completed = state.get("completed_personas", [])
    if persona_id not in completed:
        completed.append(persona_id)
    state["completed_personas"] = completed
    save_state(product_slug, state)

    remaining = [p for p in valid if p not in completed]
    ready = len(completed) == 6

    return {
        "persona_marked": persona_id,
        "completed_personas": completed,
        "remaining_personas": remaining,
        "ready_for_report": ready,
        "message": f"✓ {persona_id} marked complete. "
                   + ("🎉 All 6 personas done — report ready!" if ready
                      else f"{len(remaining)} persona(s) remaining: {', '.join(remaining)}"),
    }


@mcp.tool()
def add_alternative(product_slug: str, alternative_name: str) -> dict:
    """
    Add an alternative/competitor product to an evaluation for side-by-side comparison.
    Claude auto-researches all 35 metrics for the alternative.

    Args:
        product_slug: Slugified name of the primary product being evaluated
        alternative_name: Name of the competitor/alternative to research (e.g. "Confluence")

    Returns:
        Auto-researched scores and U-Index for the alternative, ready for comparison.
    """
    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'."}

    alt_slug = slugify(alternative_name)
    use_case = state.get("use_case", "")

    # Research the alternative
    alt_scores = {}
    alt_evidence = {}
    batch_size = 7
    for i in range(0, len(METRICS), batch_size):
        batch = METRICS[i:i + batch_size]
        try:
            result = claude_score(alternative_name, use_case, batch)
            alt_scores.update(result.get("scores", {}))
            alt_evidence.update(result.get("evidence", {}))
        except Exception:
            pass

    # Save alt scores separately
    alt_state = {
        "product": alternative_name,
        "product_slug": alt_slug,
        "use_case": use_case,
        "scores": alt_scores,
        "evidence": alt_evidence,
        "is_alternative": True,
        "compared_against": product_slug,
    }
    save_state(f"{product_slug}__alt__{alt_slug}", alt_state)

    # Register in primary state
    alts = state.get("alternatives", [])
    alts = [a for a in alts if a["slug"] != alt_slug]  # dedupe
    alts.append({"name": alternative_name, "slug": alt_slug})
    state["alternatives"] = alts
    save_state(product_slug, state)

    alt_u = calc_u_index(alt_scores)
    alt_verdict = get_verdict(alt_u)

    return {
        "alternative": alternative_name,
        "alt_slug": alt_slug,
        "u_index": alt_u,
        "verdict": alt_verdict["label"],
        "verdict_detail": alt_verdict["sub"],
        "scored_metrics": len(alt_scores),
        "scores": alt_scores,
        "message": f"Alternative '{alternative_name}' researched. U-Index: {alt_u}/5 ({alt_verdict['label']}). "
                   f"Use compare_alternatives to see side-by-side.",
    }


@mcp.tool()
def compare_alternatives(product_slug: str, filter_type: str = "all") -> dict:
    """
    Compare the primary product against all added alternatives across all 35 metrics.

    Args:
        product_slug: Slugified name of the primary product
        filter_type: What to show — "all" (all metrics), "blockers" (primary score ≤1 in critical stages),
                     "gaps" (metrics where an alternative scores higher than primary)

    Returns:
        Side-by-side comparison table, winner per metric, stage-level scores, and overall winner.
    """
    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'."}

    primary_scores = state.get("scores", {})
    alts = state.get("alternatives", [])

    if not alts:
        return {"error": "No alternatives added. Use add_alternative first."}

    # Load all alt scores
    all_products = [{"name": state["product"], "slug": product_slug, "scores": primary_scores, "is_primary": True}]
    for alt in alts:
        alt_state = load_state(f"{product_slug}__alt__{alt['slug']}")
        all_products.append({
            "name": alt["name"],
            "slug": alt["slug"],
            "scores": alt_state.get("scores", {}) if alt_state else {},
            "is_primary": False,
        })

    # Filter metrics
    if filter_type == "blockers":
        filtered = [m for m in METRICS if m["stage"] in (2,4,5)
                    and primary_scores.get(m["id"]) is not None
                    and primary_scores[m["id"]] <= 1]
    elif filter_type == "gaps":
        filtered = [m for m in METRICS
                    if any((p["scores"].get(m["id"]) or 0) > (primary_scores.get(m["id"]) or 0)
                           for p in all_products if not p["is_primary"])]
    else:
        filtered = METRICS

    # Build comparison rows
    comparison = []
    for metric in filtered:
        row = {"metric_id": metric["id"], "metric_name": metric["name"], "stage": metric["stage"], "owner": metric["owner"]}
        scores_row = {}
        for prod in all_products:
            scores_row[prod["name"]] = prod["scores"].get(metric["id"])
        row["scores"] = scores_row
        max_score = max((v for v in scores_row.values() if v is not None), default=None)
        row["winners"] = [name for name, s in scores_row.items() if s == max_score and s is not None]
        row["primary_leads"] = (scores_row.get(state["product"]) or 0) == max_score
        comparison.append(row)

    # Stage summary
    stage_summary = []
    for stage in STAGES:
        ms = [m for m in METRICS if m["stage"] == stage["id"]]
        stage_row = {"stage": stage["id"], "name": stage["name"]}
        for prod in all_products:
            sc = [prod["scores"].get(m["id"]) for m in ms if prod["scores"].get(m["id"]) is not None]
            stage_row[prod["name"]] = round(sum(sc) / (len(ms) * 5) * 5, 2) if sc else 0
        stage_summary.append(stage_row)

    # Overall scores
    overall = {prod["name"]: calc_u_index(prod["scores"]) for prod in all_products}
    overall_winner = max(overall, key=overall.get)

    return {
        "filter_applied": filter_type,
        "metrics_shown": len(comparison),
        "overall_scores": overall,
        "overall_winner": overall_winner,
        "overall_winner_is_primary": overall_winner == state["product"],
        "stage_summary": stage_summary,
        "metric_comparison": comparison,
        "gaps_count": len([r for r in comparison if not r["primary_leads"]]),
        "message": f"Overall winner: {overall_winner} ({overall[overall_winner]}/5). "
                   + (f"Primary '{state['product']}' leads." if overall_winner == state["product"]
                      else f"⚠️ Alternative '{overall_winner}' outperforms primary on overall U-Index."),
    }


@mcp.tool()
def get_report(product_slug: str) -> dict:
    """
    Generate the full evaluation report as structured JSON. Includes U-Index,
    per-stage scores, all metric scores with owners, blockers, alternatives comparison,
    and a final procurement recommendation.

    Args:
        product_slug: Slugified product name (e.g. "notion")

    Returns:
        Complete evaluation report ready for export or decision-making.
    """
    state = load_state(product_slug)
    if not state:
        return {"error": f"No evaluation found for slug '{product_slug}'."}

    scores = state.get("scores", {})
    u_index = calc_u_index(scores)
    verdict = get_verdict(u_index)
    blockers = get_blockers(scores)

    # Stage breakdown
    stages_report = []
    for stage in STAGES:
        ms = [m for m in METRICS if m["stage"] == stage["id"]]
        scored = [m for m in ms if scores.get(m["id"]) is not None]
        avg = (sum(scores[m["id"]] for m in scored) / (len(ms) * 5) * 5) if scored else 0
        stages_report.append({
            "stage_id": stage["id"],
            "stage_name": stage["name"],
            "weight": stage["weight"],
            "stage_score": round(avg, 2),
            "contribution_to_u_index": round(avg * stage["weight"], 3),
            "metrics": [
                {
                    "id": m["id"],
                    "name": m["name"],
                    "owner": m["owner"],
                    "score": scores.get(m["id"]),
                    "evidence": state.get("evidence", {}).get(m["id"], ""),
                    "notes": state.get("notes", {}).get(m["id"], ""),
                    "is_blocker": m["stage"] in (2, 4, 5) and (scores.get(m["id"]) or 999) <= 1,
                }
                for m in ms
            ],
        })

    # Alternatives summary
    alts_summary = []
    for alt in state.get("alternatives", []):
        alt_state = load_state(f"{product_slug}__alt__{alt['slug']}")
        if alt_state:
            alt_u = calc_u_index(alt_state.get("scores", {}))
            alts_summary.append({
                "name": alt["name"],
                "u_index": alt_u,
                "verdict": get_verdict(alt_u)["label"],
                "delta_vs_primary": round(alt_u - u_index, 2),
            })

    # Recommendation
    if blockers:
        recommendation = "DO_NOT_PROCURE_YET"
        recommendation_detail = f"{len(blockers)} procurement blocker(s) must be resolved before approval."
    elif u_index >= 4.0:
        recommendation = "RECOMMEND"
        recommendation_detail = "Strong enterprise-ready score. Proceed with procurement."
    elif u_index >= 3.0:
        recommendation = "CONDITIONAL_APPROVE"
        recommendation_detail = "Approvable with monitoring. Document conditions before signing."
    elif u_index >= 2.0:
        recommendation = "CONDITIONAL_PILOT"
        recommendation_detail = "Consider a limited pilot with vendor commitments on gaps."
    else:
        recommendation = "DO_NOT_PROCURE"
        recommendation_detail = "Not enterprise-ready. Evaluate alternatives."

    return {
        "report_type": "SaaS Usability Index Evaluation",
        "product": state.get("product"),
        "use_case": state.get("use_case", ""),
        "u_index": u_index,
        "verdict": verdict["label"],
        "verdict_detail": verdict["sub"],
        "recommendation": recommendation,
        "recommendation_detail": recommendation_detail,
        "scored_metrics": len([s for s in scores.values() if s is not None]),
        "completed_personas": state.get("completed_personas", []),
        "blockers": [
            {"id": b["id"], "name": b["name"], "stage": b["stage"], "score": scores[b["id"]]}
            for b in blockers
        ],
        "stages": stages_report,
        "alternatives_considered": alts_summary,
        "alternatives_winner": max(alts_summary, key=lambda a: a["u_index"])["name"] if alts_summary else None,
    }


@mcp.tool()
def list_evaluations() -> dict:
    """
    List all evaluations stored on this server.

    Returns:
        All evaluations with their current U-Index and verdict.
    """
    evals = []
    for p in DATA_DIR.glob("*.json"):
        if "__alt__" in p.stem:
            continue
        try:
            state = json.loads(p.read_text())
            scores = state.get("scores", {})
            u = calc_u_index(scores)
            evals.append({
                "product": state.get("product"),
                "slug": p.stem,
                "u_index": u,
                "verdict": get_verdict(u)["label"],
                "scored_metrics": len([s for s in scores.values() if s is not None]),
                "alternatives": [a["name"] for a in state.get("alternatives", [])],
                "completed_personas": len(state.get("completed_personas", [])),
            })
        except Exception:
            pass
    return {"evaluations": evals, "count": len(evals)}


if __name__ == "__main__":
    mcp.run()
